name: sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install tsx -g
      - run: tsx ./format.mts
      - uses: creyD/prettier_action@v4.0
        with:
          prettier_options: ./*.json -w --loglevel=warn
          same_commit: true
      - uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:MillCloud/glossary-json.git
          destination-repo: git@gitee.com:MillCloud/glossary-json.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
