# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Sort
        run: node ./sort.js

      - name: Prettify
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write **/*.json
          same_commit: true

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:MillCloud/glossary-json.git
          destination-repo: git@gitee.com:MillCloud/glossary-json.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
